name: Download dan Save Module

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  Module:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        # Initialize npm if package.json doesn't exist
        if [ ! -f package.json ]; then
          npm init -y
        fi
        
        # Create directories
        mkdir -p saved_modules
        
        # Install packages
        npm install @tensorflow/tfjs-node --save
        npm install @angular/cli --save
        npm install @angular/core --save
        npm install @polymer/polymer --save
        
        # Copy to saved_modules
        rm -rf saved_modules/*
        cp -r node_modules/ saved_modules/
        
    - name: Update package.json timestamp
      run: |
        CURRENT_DATE=$(date '+%Y-%m-%d')
        jq --arg date "$CURRENT_DATE" '.lastUpdate = $date' package.json > temp.json && mv temp.json package.json
        
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Commit Changes
      run: |
        git add saved_modules/
        git add package.json
        git add package-lock.json || true
        git status
        
    - name: Create Commit
      run: |
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update modules - $(date +'%Y-%m-%d')"
          git push origin main
        fi
